#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-container
        #image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        image: ayzohairy/petclinic:3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu}}
            memory: {{ .Values.resources.limits.memory}}
          requests:
            cpu: {{ .Values.resources.limits.cpu}}
            memory: {{ .Values.resources.limits.memory}}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: my-registry-secret



