{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
secrets:
- name: my-registry-secret
metadata:
  name: {{ template "petclinic.serviceAccountName" . }}
  labels:
{{ include "petclinic.labels" . | indent 4 }}
{{- end -}}
